<Project>
  <PropertyGroup Label="Default Properties (not applied automatically)">
    <RepoRootNamespace>angelof.dev</RepoRootNamespace>
    <DefaultTargetFramework>net10.0</DefaultTargetFramework>
    <DefaultRootNamespace>$(RepoRootNamespace).$(MSBuildProjectName)</DefaultRootNamespace>
    <DefaultAssemblyName>$(DefaultRootNamespace)</DefaultAssemblyName>
  </PropertyGroup>

  <PropertyGroup Label="Repository Layout">
    <WorktreeRootDirectory>$(MSBuildThisFileDirectory)</WorktreeRootDirectory>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)Artifacts/$(SolutionName)</ArtifactsPath>
  </PropertyGroup>
</Project>
