<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <RootNamespace>tests.$(RepoRootNamespace)</RootNamespace>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Sources\StandardLibrary\StandardLibrary.csproj"/>
  </ItemGroup>
</Project>
